//<auto-generated> Abi auto generated contract. 2023-02-26T12:01:49</auto-generated>
using System.Numerics;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.BlockchainProcessing.Processor;
using Nethereum.Contracts;
using Nethereum.RPC.Eth.DTOs;
using Nethereum.Web3;

namespace biswapAuction
{
    public class SolidityISwapFeeRewardWithRB
    {
    }

    public class SolidityAuction
    {
        public class TokenPair
        {
            public String Nft { get; set; }

            public BigInteger TokenId { get; set; }
        }

        public class Inventory
        {
            public String Pair { get; set; }

            public string Seller { get; set; }

            public string Bidder { get; set; }

            public String Currency { get; set; }

            public BigInteger AskPrice { get; set; }

            public BigInteger BidPrice { get; set; }

            public BigInteger NetBidPrice { get; set; }

            public BigInteger StartBlock { get; set; }

            public BigInteger EndTimestamp { get; set; }

            public String Status { get; set; }
        }

        public class RoyaltyStr
        {
            public BigInteger Rate { get; set; }

            public string Receiver { get; set; }

            public bool Enable { get; set; }
        }

        public bool _canReceive { get; set; }

        public String Auctions { get; set; }

        public String NftBlacklist { get; set; }

        public String NftForAccrualRB { get; set; }

        public String DealTokensWhitelist { get; set; }

        public String AuctionNftIndex { get; set; }

        public String UserFee { get; set; }

        public String Royalty { get; set; }

        public BigInteger MAX_DEFAULT_FEE { get; set; }

        public string TreasuryAddress { get; set; }

        public BigInteger DefaultFee { get; set; }

        public BigInteger ExtendEndTimestamp { get; set; }

        public BigInteger MinAuctionDuration { get; set; }

        public BigInteger ProlongationTime { get; set; }

        public BigInteger RateBase { get; set; }

        public BigInteger BidderIncentiveRate { get; set; }

        public BigInteger BidIncrRate { get; set; }

        public String FeeRewardRB { get; set; }

        public bool FeeRewardRBIsEnabled { get; set; }
    }

    public class SolidityAddress
    {
    }

    public class SolidityContext
    {
    }

    public class SolidityIERC20
    {
    }

    public class SolidityIERC165
    {
    }

    public class SolidityIERC721
    {
    }

    public class SolidityIERC721Receiver
    {
    }

    public class SolidityOwnable
    {
        public string _owner { get; set; }
    }

    public class SolidityPausable
    {
        public bool _paused { get; set; }
    }

    public class SolidityReentrancyGuard
    {
        public BigInteger _NOT_ENTERED { get; set; }

        public BigInteger _ENTERED { get; set; }

        public BigInteger _status { get; set; }
    }

    public class SoliditySafeERC20
    {
    }
}